System\CompasBundle\Entity\TBIssueStatusTemplate:
    type: entity
    indexes: {  }
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        Name:
            type: string
            length: 255
            nullable: true
    oneToMany:
        tbissuestatustemplatedetails:
            targetEntity: TBIssueStatusTemplateDetail
            mappedBy: tbissuestatustemplate
    manyToOne: {  }
    manyToMany: {  }
