System\CompasBundle\Entity\TBIssueStatusTemplateDetail:
    type: entity
    indexes: {  }
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        IssueStatusTemplateId:
            type: integer
            nullable: true
        Name:
            type: string
            length: 255
            nullable: true
        Description:
            type: string
            length: 255
            nullable: true
        IconFileName:
            type: string
            length: 255
            nullable: true
        SortNo:
            type: integer
            nullable: true
    oneToMany: {  }
    manyToOne:
        tbissuestatustemplate:
            targetEntity: TBIssueStatusTemplate
            inversedBy: tbissuestatustemplatedetails
            joinColumns:
                IssueStatusTemplateId:
                    referencedColumnName: id
    manyToMany: {  }
