System\CompasBundle\Entity\TBIssuePriority:
    type: entity
    indexes: {  }
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        ProjectId:
            type: integer
            nullable: true
        Name:
            type: string
            length: 255
            nullable: true
        Description:
            type: string
            length: 255
            nullable: true
        IconFileName:
            type: string
            length: 255
            nullable: true
        DeleteFlug:
            type: boolean
            nullable: true
        SortNo:
            type: integer
            nullable: true
    oneToMany:
        tbissuereplys:
            targetEntity: TBIssueReply
            mappedBy: tbissuepriority
    manyToOne:
        tbproject:
            targetEntity: TBProject
            inversedBy: tbissueprioritys
            joinColumns:
                ProjectId:
                    referencedColumnName: id
    manyToMany: {  }
